safe-global/safe-apps-list

- config/appsList.js
- public/gnosis-default.applist.json
Closes #1
Update Sablier app to include MPL token
> Update Sablier app

- config/appsList.js
- public/gnosis-default.applist.json
> add mStable app

- config/appsList.js
- public/gnosis-default.applist.json
- src/buildList.js
This PR:
- closes #4 
- add liquity's new frontend ipfs hash
> Update liquity app

- .github/ISSUE_TEMPLATE/safe-app-request.md
This will add the template on how to ask for changes for a safe app as requested in #2
> Add Safe app request template

- config/appsList.js
- public/gnosis-default.applist.json
Only change is new token listed, [MFI](https://etherscan.io/token/0xaa4e3edb11afa93c41db59842b29de64b72e355b).
> Update sablier to v0.2.5

- config/appsList.js
- public/gnosis-default.applist.json
Closes #13 
Update Balancer Exchange to latest version fixing problem with Infura API key
> Update Balancer Exchange app

- config/appsList.js
- public/gnosis-default.applist.json
> Add stakewise app

- config/appsList.js
- public/gnosis-default.applist.json
See https://github.com/paulrberg/sablier-safe-app/releases/tag/v0.2.8
> feat: update sablier to v0.2.8

- config/appsList.js
- public/gnosis-default.applist.json
There's a small problem that for some strategies it opens the app in a new tab, the other ones work fine. I reported it to the Furucombo team.
> Add furucombo app

- config/appsList.js
- package.json
- public/gnosis-default.applist.json
> Add paraswap app

- public/gnosis-default.applist.json
In the PR https://github.com/gnosis/safe-apps-list/pull/32, we forgot to update the app list, this PR fixes that
> Update app list

- config/appsList.js
- public/gnosis-default.applist.json
Now when https://github.com/gnosis/safe-react/pull/2188 is live, we can finally add curve
> Add curve safe app

- config/appsList.js
- public/gnosis-default.applist.json
Besides listing two new tokens ($PLA and $XSUSHI), this PR also changes the description of the Sablier app to "Stream money with Sablier".
> feat: update sablier to v0.2.9

- config/appsList.js
- public/gnosis-default.applist.json
https://github.com/paulrberg/sablier-safe-app/releases/tag/v0.2.10
> feat: update sablier to v0.2.10

- config/appsList.js
- public/gnosis-default.applist.json
Use latest version of transaction builder
> Update transaction builder to v1.1.0

- config/appsList.js
- public/gnosis-default.applist.json
> Add zerion safe app

- config/appsList.js
- public/gnosis-default.applist.json
Update TX Builder to show to field for all address/abi inputs
This fixes the issue where loading an ABI using a Master Copy address didn't show the to field, not allowing users to interact with the desired address
> Upgrade TX Builder to v1.2.0

- config/appsList.js
- public/gnosis-default.applist.json
> Add Oasis Borrow

- config/appsList.js
- public/gnosis-default.applist.json
> Add CSV Airdrop

- config/appsList.js
- public/gnosis-default.applist.json
Changelog:
- Update the Gnosis SDK to the latest versions (safe-apps-react-sdk@4.0.0 and safe-react-components@0.6.0)
- Update the graphql queries to match the [latest subgraph schema](https://thegraph.com/explorer/subgraph/sablierhq/sablier)
- Lots of minor improvements, bug fixes, etc.
See release: https://github.com/paulrberg/sablier-safe-app/releases/tag/v1.0.0.
> feat: update sablier to v1.0.0

- .github/ISSUE_TEMPLATE/safe-app-request.md
Updates outdated/broken links to Safe docs in the issue template.
> Update docs links

- .github/ISSUE_TEMPLATE/safe-app-request.md
To enhance the review process, this PR adds a “Reviewer” item to the PR template checklist. This ensures that access to any private repositories has been granted to the safe reviewer before submission.
> Add reviewer item to pr template checklist

- .github/ISSUE_TEMPLATE/safe-app-request.md
This PR adds Telegram to the list of social networks of safe app request issue template.
> Add Telegram to social media
